### ISSUE TITLE
Calling nidaqmx GetExtendedErrorInfo via gRPC is not reliable because it uses thread-local storage

### ISSUE THREAD

**Issue by bkeryan** [ni/grpc-device#684]
[nidaqmx.proto](https://github.com/ni/grpc-device/blob/main/generated/nidaqmx/nidaqmx.proto#L182) supports the `DAQmxGetExtendedErrorInfo` function. Calling this function via gRPC is not reliable because it uses thread-local storage.

Depending which server thread is used to handle this request, it may return the correct error message, an empty string, or an incorrect error message.

Steps to reproduce: 
1. Change one of the DAQmx examples to make multiple concurrent GetExtendedErrorInfo requests:
```
def raise_if_error(response):
    """Raise an exception if an error was returned."""
    if response.status != 0:
        response = client.GetExtendedErrorInfo.future(nidaqmx_types.GetExtendedErrorInfoRequest())
        response2 = client.GetExtendedErrorInfo.future(nidaqmx_types.GetExtendedErrorInfoRequest())
        response3 = client.GetExtendedErrorInfo.future(nidaqmx_types.GetExtendedErrorInfoRequest())
        raise Exception(f"Error: {response3.result().error_string}")
```
2. Run NI IO Trace and enable the ThreadID column.
3. Run the example with an invalid device identifier. Normally, this would display a "Device identifier is invalid" error, but this issue may cause it to display an empty string or an incorrect error message.
```
(.venv) PS Z:\grpc-device\examples\nidaqmx> python .\analog-input.py localhost 31763 Dev42/ai0
Traceback (most recent call last):
  File ".\analog-input.py", line 71, in <module>
    raise_if_error(
  File ".\analog-input.py", line 63, in raise_if_error
    raise Exception(f"Error: {response3.result().error_string}")
Exception: Error: The requested memory could not be allocated.
Status Code: -50352
```
NI IO Trace will show which thread was used to handle each call to `DAQmxGetExtendedErrorInfo`:
![image](https://user-images.githubusercontent.com/17914399/180328166-6c585844-7e17-4f7e-afad-1c0974b7c797.png)

[AB#2085088](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2085088)

**Comment by bkeryan** [comment]
I validated that `GetExtendedErrorInfo` has been removed from `nidaqmx.proto` and is called from `NiDAQmxService::ConvertApiErrorStatusForTaskHandle`, which should always be called on the same thread that returned the error.
